const express = require("express");
const router = express.Router();
const register = require("./register");
const login = require("./login");
const add_entry = require("./add_entry");
const spendings = require("./spendings");
const deleteTransaction = require("./deleteTransaction");
const updateTransaction = require("./updateTransaction");
const crypto = require("./crypto");
const dailyreport = require("./dailyreport");
const weeklyreport = require("./weeklyreport");
const weeklyreport2 = require("./weeklyreport2");
const monthlyreportdate = require("./monthlyreportdate");
const monthlyreportcategory = require("./monthlyreportcategory");
const updateincome = require("./updateincome");
const yearlydate = require("./yearlydate");
const yearlycategory = require("./yearlycategory");
const updatesaving = require("./updatesaving");
const showincome = require("./showincome");
const showexpences = require("./showexpences");
const showcryptoexpence = require("./showcryptoexpence");
const showstocksexpence = require("./showstocksexpence");
const setreminder = require("./setreminder");
const printreminder = require("./printreminder");
const deletereminder = require("./deletereminder");
const stocks = require("./stocks");
const sendreminder = require("./sendreminder");
const creategroup = require("./creategroup");
const addmember = require("./addmember");
const verifygroupuser = require("./verifygroupuser");
const printgroups = require("./printgroups");
const countMembers = require("./countMembers");
const getcreatorname = require("./getcreatorname");
const showeditmodal = require("./showeditmodal");

router.post("/register", register);
router.post("/login", login);
router.post("/add_entry", add_entry);
router.post("/spending", spendings);
router.post("/dailyreport", dailyreport);
router.post("/weeklyreport", weeklyreport);
router.post("/weeklyreport2", weeklyreport2);
router.post("/monthlyreportdate", monthlyreportdate);
router.post("/monthlyreportcategory", monthlyreportcategory);
router.post("/yearlydate", yearlydate);
router.post("/yearlycategory", yearlycategory);
router.post("/deleteTransaction/", deleteTransaction);
router.post("/updateTransaction/", updateTransaction);
router.post("/crypto", crypto);
router.post("/stocks", stocks);
router.post("/updateincome", updateincome);
router.post("/updatesaving/", updatesaving);
router.post("/showincome/", showincome);
router.post("/showexpences", showexpences);
router.post("/showcryptoexpence", showcryptoexpence);
router.post("/showstocksexpence", showstocksexpence);
router.post("/setreminder", setreminder);
router.post("/printreminder", printreminder);
router.post("/deletereminder", deletereminder);
router.post("/sendreminder", sendreminder);
router.post("/creategroup", creategroup);
router.post("/addmember", addmember);
router.post("/verifygroupuser", verifygroupuser);
router.post("/printgroups", printgroups);
router.post("/countMembers", countMembers);
router.post("/getcreatorname", getcreatorname);
router.post("/showeditmodal", showeditmodal);

module.exports = router;
